In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math

In [2]:
#nodes data
nodes_data = pd.read_csv('dataset/a280_data.csv',header = None)
nodes_data

0    1    2
0      1  288  149
1      2  288  129
2      3  270  133
3      4  256  141
4      5  256  157
..   ...  ...  ...
275  276  236  145
276  277  246  141
277  278  252  125
278  279  260  129
279  280  280  133

[280 rows x 3 columns]

In [3]:
#distance calculation 
def distance_cal(df):
    dist = []
    for i in range (0,len(df)):
        distances = []
        for j in range (0,len(df)):
            if i == j :
                distances.append(0.0)
            else :
                val = math.sqrt(math.pow(df.loc[i][1] - df.loc[j][1], 2) + math.pow(df.loc[i][2] - df.loc[j][2], 2));
                distances.append(val)
        dist.append(distances)
    return dist              

In [4]:
df_data = distance_cal(nodes_data) #distance between all nodes
df_data

[[0.0,
  20.0,
  24.08318915758459,
  32.984845004941285,
  32.984845004941285,
  42.7551166528639,
  55.71355310873648,
  63.245553203367585,
  61.18823416311342,
  70.8801805866774,
  78.587530817554,
  86.34813257969161,
  94.14881836751856,
  101.9803902718557,
  92.77930803794561,
  100.07996802557443,
  116.06894502837527,
  124.06449935416659,
  132.06059215375342,
  140.05713120009278,
  148.05404418657398,
  141.4213562373095,
  125.60254774486066,
  117.71151175649729,
  133.5065541462291,
  149.34523762075577,
  157.2768260107,
  165.21501142450705,
  172.41809649801846,
  184.04347312523745,
  184.39088914585776,
  185.0837648201484,
  198.6454127333425,
  208.153789300123,
  224.1428116179504,
  224.57070156189118,
  232.86047324524614,
  232.31013753170566,
  232.03448019637082,
  232.03448019637082,
  232.31013753170566,
  232.86047324524614,
  233.68354670365648,
  249.57563983690395,
  248.8051446413438,
  248.29015284541592,
  248.03225596683993,
  248.03225596683993,

In [5]:
dist_data = pd.DataFrame(df_data)
dist_data

0          1          2          3          4          5    \
0     0.000000  20.000000  24.083189  32.984845  32.984845  42.755117   
1    20.000000   0.000000  18.439089  34.176015  42.520583  50.477718   
2    24.083189  18.439089   0.000000  16.124515  27.784888  33.941125   
3    32.984845  34.176015  16.124515   0.000000  16.000000  18.867962   
4    32.984845  42.520583  27.784888  16.000000   0.000000  10.000000   
..         ...        ...        ...        ...        ...        ...   
275  52.153619  54.405882  36.055513  20.396078  23.323808  15.620499   
276  42.755117  43.680659  25.298221  10.000000  18.867962  16.000000   
277  43.266615  36.221541  19.697716  16.492423  32.249031  32.557641   
278  34.409301  28.000000  10.770330  12.649111  28.284271  31.304952   
279  17.888544   8.944272  10.000000  25.298221  33.941125  41.617304   

           6          7          8          9    ...        270        271  \
0    55.713553  63.245553  61.188234  70.880181  ...  92.086915  84.095184   
1    65.604878  72.111026  68.000000  78.892332  ...  93.380940  85.510233   
2    49.517674  55.317267  50.477718  61.611687  ...  74.966659  67.082039   
3    34.409301  39.597980  34.409301  45.607017  ...  60.133186  52.153619   
4    23.323808  30.463092  28.284271  37.947332  ...  61.188234  53.366656   
..         ...        ...        ...        ...  ...        ...        ...   
275  24.000000  25.298221  17.888544  28.844410  ...  40.000000  32.000000   
276  29.732137  33.286634  26.907248  38.209946  ...  50.159745  42.190046   
277  46.818800  50.119856  43.266615  54.405882  ...  59.464275  52.000000   
278  46.647615  51.224994  45.254834  56.568542  ...  65.969690  58.240879   
279  56.850682  63.245553  59.059292  69.971423  ...  84.852814  76.941536   

           272        273        274        275        276        277  \
0    76.105190  68.117545  60.133186  52.153619  42.755117  43.266615   
1    77.665951  69.856997  62.096699  54.405882  43.680659  36.221541   
2    59.228372  51.419841  43.680659  36.055513  25.298221  19.697716   
3    44.181444  36.221541  28.284271  20.396078  10.000000  16.492423   
4    45.607017  37.947332  30.463092  23.323808  18.867962  32.249031   
..         ...        ...        ...        ...        ...        ...   
275  24.000000  16.000000   8.000000   0.000000  10.770330  25.612497   
276  34.234486  26.305893  18.439089  10.770330   0.000000  17.088007   
277  44.721360  37.735925  31.240999  25.612497  17.088007   0.000000   
278  50.596443  43.081318  35.777088  28.844410  18.439089   8.944272   
279  69.050706  61.188234  53.366656  45.607017  34.928498  29.120440   

           278        279  
0    34.409301  17.888544  
1    28.000000   8.944272  
2    10.770330  10.000000  
3    12.649111  25.298221  
4    28.284271  33.941125  
..         ...        ...  
275  28.844410  45.607017  
276  18.439089  34.928498  
277   8.944272  29.120440  
278   0.000000  20.396078  
279  20.396078   0.000000  

[280 rows x 280 columns]

In [6]:
a = np.random.randint(0, 2, size = (len(df_data), len(df_data)), dtype = int)
print(a)

[[0 1 1 ... 0 1 1]
 [0 0 1 ... 1 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [1 1 1 ... 0 1 0]
 [1 1 1 ... 1 0 0]
 [1 0 1 ... 0 1 1]]


In [7]:
wt_cal = np.empty(len(df_data))
for i in range (0,len(df_data)):
    weight_sum = 0
    for j in range (0,len(a)):
        weight_sum += a[i][j] * df_data[i][j]
    wt_cal[i] = weight_sum

In [8]:
wt_cal

array([23213.72207372, 23142.26550464, 20129.85405361, 20719.56957834,
       19629.94425815, 21071.97516945, 20264.08659236, 18515.76532799,
       19699.58918975, 19874.95088209, 20238.67475255, 19842.66048198,
       17808.83626966, 18617.11060062, 12965.25781329, 16167.77205574,
       15544.70268821, 14888.91718752, 17051.04790154, 14290.72555983,
       14274.07919804, 17819.75441888, 17997.51475125, 16487.09714578,
       17918.32517916, 15750.50123179, 16588.7123878 , 15739.91662839,
       16420.14329981, 15494.62764005, 17527.82018354, 16896.83895462,
       18260.75453941, 16449.34235151, 15952.33763317, 18272.62505937,
       19032.84344972, 17325.51509008, 20266.63470999, 19871.20417527,
       18273.57330422, 17449.40225625, 18710.57121362, 15847.22474541,
       19898.03230573, 18481.11204622, 17931.28397018, 19722.40347544,
       21439.07072492, 18800.76138365, 20503.84617633, 21422.5060761 ,
       22031.66455529, 20459.26430605, 18240.15888275, 19307.24984323,
      

In [12]:
min(wt_cal)/

11317.78750541811

In [9]:
#df_data.to_csv('dataset/nodes_distance_file.csv',index=False)
np.savetxt("dataset/nodes_distance_file.csv", 
           df_data,
           delimiter =", ")  #saving the distnce files for further 

In [10]:
text_file = open("dataset/n279.txt", "r")   # reading data from the given file
data = text_file.read().split()
items_data = pd.DataFrame(columns=['Value', 'Weight', 'Node'])
items = []
weights = []
nodes = []
for val in range(1,len(data)):
    if val+2 < len(data):
        items.append(data[val])
        weights.append(data[val+1])
        nodes.append(data[val+2])
       # df = {'Value': data[val], 'Weight' : data[val+1], 'Node': data[val+2]}
        #listn = (data[val], data[val+1],data[val+2])
        #items_data.append(df)
        val+=3
items_data
items_data

Empty DataFrame
Columns: [Value, Weight, Node]
Index: []

In [11]:
data

['1',
 '101',
 '1',
 '2',
 '2',
 '202',
 '2',
 '3',
 '3',
 '404',
 '4',
 '4',
 '4',
 '202',
 '2',
 '5',
 '5',
 '996',
 '896',
 '6',
 '6',
 '1992',
 '1792',
 '7',
 '7',
 '3984',
 '3584',
 '8',
 '8',
 '467',
 '367',
 '9',
 '9',
 '934',
 '734',
 '10',
 '10',
 '1868',
 '1468',
 '11',
 '11',
 '790',
 '690',
 '12',
 '12',
 '790',
 '690',
 '13',
 '13',
 '713',
 '613',
 '14',
 '14',
 '1426',
 '1226',
 '15',
 '15',
 '2852',
 '2452',
 '16',
 '16',
 '974',
 '874',
 '17',
 '17',
 '974',
 '874',
 '18',
 '18',
 '222',
 '122',
 '19',
 '19',
 '444',
 '244',
 '20',
 '20',
 '888',
 '488',
 '21',
 '21',
 '666',
 '366',
 '22',
 '22',
 '586',
 '486',
 '23',
 '23',
 '1172',
 '972',
 '24',
 '24',
 '1172',
 '972',
 '25',
 '25',
 '923',
 '823',
 '26',
 '26',
 '923',
 '823',
 '27',
 '27',
 '563',
 '463',
 '28',
 '28',
 '1126',
 '926',
 '29',
 '29',
 '563',
 '463',
 '30',
 '30',
 '689',
 '589',
 '31',
 '31',
 '1378',
 '1178',
 '32',
 '32',
 '1378',
 '1178',
 '33',
 '33',
 '425',
 '325',
 '34',
 '34',
 '850',
 '6

In [9]:
items_data = pd.DataFrame(columns=['Value', 'Weight', 'Node'])

In [11]:
items_data

Empty DataFrame
Columns: [Value, Weight, Node]
Index: []